Updated bcgov/user-count package steps

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -152,26 +152,28 @@ jobs:
         id: check_package
         run: |
           echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
-          npm view @bcgov/user-count version ; echo "Package does not exist"
+          npm view @bcgov/user-count version || echo "Package does not exist"
         env:
           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
       - name: Create and publish package if it doesn't exist
-        if: steps.check_package.outcome == 'failure'
         run: |
-          echo "module.exports = { userCount: 0 };" > index.js
-          echo "{
-            \"name\": \"@bcgov/user-count\",
-            \"version\": \"1.0.0\",
-            \"main\": \"index.js\",
-            \"repository\": {
-              \"type\": \"git\",
-              \"url\": \"git+https://github.com/bcgov/your-repository.git\"
-            },
-            \"author\": \"\",
-            \"license\": \"ISC\"
-          }" > package.json
-          npm publish
+          PACKAGE_VERSION=$(npm view @bcgov/user-count version || echo "not found")
+          if [ "$PACKAGE_VERSION" == "not found" ]; then
+            echo "module.exports = { userCount: 0 };" > index.js
+            echo "{
+              \"name\": \"@bcgov/user-count\",
+              \"version\": \"1.0.0\",
+              \"main\": \"index.js\",
+              \"repository\": {
+                \"type\": \"git\",
+                \"url\": \"git+https://github.com/bcgov/your-repository.git\"
+              },
+              \"author\": \"\",
+              \"license\": \"ISC\"
+            }" > package.json
+            npm publish
+          fi
         env:
           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
